language: python
python:
  - "3.6"
before_install:
  - unzip test-repos.zip
  - cd test-repos
  - git clone https://github.com/rails/rails.git
  - cd ..
install:
  - pip install -r requirements.txt
script:
  - pytest -v -s