language: python
notifications:
    slack: pydriller:GY8wzJPkOMy22cPAH7umESp9

os:
  - linux
  - osx

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

matrix:
    include:
        # Use the built in venv for linux builds
        - os: linux
          python: 3.4
        - os: linux
          python: 3.5
        - os: linux
          python: 3.6
        - os: linux
          python: 3.7
        # Use generic language for osx
        - os: osx
          language: generic


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list python &>/dev/null || brew install python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list python3 &>/dev/null || brew install python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install pyenv-virtualenv; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y python; fi
  - unzip test-repos.zip
  - git clone https://github.com/apache/hadoop.git test-repos/hadoop

install:
  - pip install -r test-requirements.txt
  - pip install codecov pytest-cov

script:
  - pytest tests/ --cov=pydriller/

after_success:
  - codecov
