language: python
notifications:
    slack: pydriller:GY8wzJPkOMy22cPAH7umESp9
python:
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - unzip test-repos.zip
  - cd test-repos
  - git clone https://github.com/apache/hadoop.git
  - cd ..
  - pip install codecov
install:
  - pip install -r requirements.txt
  - pip install requests
script:
  - pytest -v -s
after_success:
  - codecov